
spring:
    application:
      name: demo2
    sql:
      init:
        mode: always
    datasource:
      driver-class-name: org.postgresql.Driver
      password: 123
      username: "postgres"
      url: jdbc:postgresql://localhost:5432/RestoranDB
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate.format_sql: true
jwt:
  secret: 984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf
  lifetime: 10m